### ISSUE TITLE
0.10 incompatible with NoobHub

### ISSUE THREAD

**Issue by TomatoCo** [KennyShields/LoveFrames#157]
When loading LoveFrames before NoobHub, NoobHub somehow calls a LoveFrames function and causes a stack trace.

http://i.imgur.com/43I3hOe.png

This error did not occur on earlier versions (I was out of the loop for a while and I last used 0.9.8.1, I believe).

The error does not occur if LoveFrames is loaded after NoobHub.

**Comment by KennyShields** [comment]
Seems to be an issue with the utf8 library that was recently added to Love Frames. The library overwrites some Lua's string functions, so thats likely what is causing the issue. I have added a configuration variable in commit 0c91c05caf62b0ca287d378abb676fe77f1ffde8 that allows the developer to enable or disable utf8 support, setting that to false should fix the issue.

**Comment by TomatoCo** [comment]
I very much appreciate this, but I'm not certain how to use it.

`loveframes = require('loveframes')
loveframes.config["ENABLE_UTF8_SUPPORT"] = false`

Is what I'm doing, but without any luck. I still get the crash. Looking at the demo this seems like the right thing, but looking at the code in init.lua, I'm not sure how the require(utf8) part could ever not get executed.

**Comment by KennyShields** [comment]
You have to change the value of the configuration variable in init.lua on line 26.

**Comment by TomatoCo** [comment]
Works great! Thanks for all the hard work you've put into this awesome project!

**Comment by KennyShields** [comment]
No problem.
